# Generated by Django 3.2.2 on 2021-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0006_pagar_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome completo')),
                ('curso', models.CharField(choices=[('Curso de informática', 'Curso de informática'), ('Curso de medicina geral', 'Curso de medicina geral'), ('Curso de electrónica', 'Curso de electrónica'), ('Curso de artes', 'Curso de artes')], max_length=23)),
                ('valor', models.DecimalField(decimal_places=5, default=1000, max_digits=10)),
                ('numero', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Número de celular')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
