# Generated by Django 3.2.2 on 2021-07-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0007_inscricoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoes',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
